### ISSUE TITLE
don't connect

### ISSUE THREAD

**Issue by amir385276** [Bardiafa/Free-V2ray-Config#1]
Hi Bardia
all of your config don't connect
I try in Smartphone and PC

thanks a lot

**Comment by Bardiafa** [comment]
Hi , 
Configs are getting updated every 10 minutes. So try again in few minutes later

Also i put some apps in readme to get better results : [Readme](https://github.com/Bardiafa/Free-V2ray-Config/blob/main/README.md).

Let me know if you get connected or not...

We are going to add some features Soon, Star the repo to be Stay Tuned.

**Comment by amir385276** [comment]
Hi again
I try to paste new config sometimes in a day, but there is no reason to connection in VPN

i do compare with your config and another config (paid) in the SNI and port we have a issue

actually maybe the other connection must be config in the V2RayNG===>Settings or NekoBox===>Settings or Nekoray===>Settings

in the end i found 6 URLtest green result in the 3 app (V2RayNG, NekoBOX, Matsuri) and it's connected to VPN but with very slow spped 
some other VPN (blueSpeedVPN, قوي ترين فيلتر شكن آمريكا) connected with 4 or 5Mb Speed in the same ADSL 
I use the ParsOnline and Fanava

also Thanks a lot

**Comment by Bardiafa** [comment]
Hi again ,

Some of the users of these configs , told me you have to import them all then try Real Delay of all configs to get best results.

The Speed of Configs is depending of how many people are using these servers so try lowest ping to get best results

I dont know about the apps you told me that are working!! Maybe they are not using V2ray at all!!

**Comment by amir385276** [comment]
Ok Thanks
