### ISSUE TITLE
The readme says nothing about the usage process in Linux

### ISSUE THREAD

**Issue by yolowex** [Bardiafa/Free-V2ray-Config#14]
> computer Windows and penguin Linux

> On Windows, we recommend using [Nekoray](https://github.com/MatsuriDayo/nekoray) or [V2rayN](https://github.com/2dust/v2rayN) client. To import a configuration file in nekoray , simply open the app then on the Program icon , select "Add profile from clipboard", and paste the configuration link. To import a configuration file in V2rayN, simply right-click on the V2rayN icon in the system tray, select "Import from clipboard", and paste the configuration link. For the official client, click on the "V" icon in the system tray and select "Import Config".

enlighten me, if I'm wrong

**Comment by Bardiafa** [comment]
Hi @yolowex ,
Thanks for creating issue , yes most of linux distributions can run nekoray that are debian based. you can visit their repo : https://github.com/MatsuriDayo/nekoray

**Comment by yolowex** [comment]
Thank you so much for the information!
