### ISSUE TITLE
subscription lists too long for apps

### ISSUE THREAD

**Issue by POORIANSARI** [Bardiafa/Free-V2ray-Config#15]
hello dear bardia 
subscription lists are too long for applications making them hanging.Can you make them into more sections?

**Comment by Bardiafa** [comment]
Hi Pooria
I have already done that :)

Subscription 1 : https://raw.githubusercontent.com/Bardiafa/Free-V2ray-Config/main/Sub1.txt

Subscription 2 : https://raw.githubusercontent.com/Bardiafa/Free-V2ray-Config/main/Sub2.txt

Subscription 3 : https://raw.githubusercontent.com/Bardiafa/Free-V2ray-Config/main/Sub3.txt

Subscription 4 : https://raw.githubusercontent.com/Bardiafa/Free-V2ray-Config/main/Sub4.txt

Subscription 5 : https://raw.githubusercontent.com/Bardiafa/Free-V2ray-Config/main/Sub5.txt

Subscription 6 : https://raw.githubusercontent.com/Bardiafa/Free-V2ray-Config/main/Sub6.txt

Subscription 7 : https://raw.githubusercontent.com/Bardiafa/Free-V2ray-Config/main/Sub7.txt

Subscription 8 : https://raw.githubusercontent.com/Bardiafa/Free-V2ray-Config/main/Sub8.txt
