### ISSUE TITLE
V2Ray Sender Telegram

### ISSUE THREAD

**Issue by Sepehr0Day** [Bardiafa/Free-V2ray-Config#21]
سلام
من مدتی هست رباتی طراحی کردم که از این مخزن
https://github.com/yebekhe/TelegramV2rayCollector
کانفیگ هارو با اجازشون استخراج میکنه, و در چنلم برای استفاده عمومی قرار میده.
اگر امکاش هست با ذکر نامتون از پرژوژتون استفاده کنم و کانفیگ هارو استخراج کنم.
ربات : https://t.me/V2RaySenderBot
چنل : https://t.me/V2RayVPNFree
ممنون

**Comment by Bardiafa** [comment]
سلام خسته نباشید @Sepehr0Day 
مشکلی نیست میتونید از لینک های ساب بنده هم استفاده کنید 🎯
این لینک ها برای مردم هستن و همه میتونن استفاده کنن🤝

> سلام من مدتی هست رباتی طراحی کردم که از این مخزن https://github.com/yebekhe/TelegramV2rayCollector کانفیگ هارو با اجازشون استخراج میکنه, و در چنلم برای استفاده عمومی قرار میده. اگر امکاش هست با ذکر نامتون از پرژوژتون استفاده کنم و کانفیگ هارو استخراج کنم. ربات : https://t.me/V2RaySenderBot چنل : https://t.me/V2RayVPNFree ممنون
